### ISSUE TITLE
(Crital) Open source

### ISSUE THREAD

**Issue by xllifi** [MrSypz/ModBugReport#6]
My friend needs this mod for 1.20.1 and I'm willing to help him backport it. Since the mod is no longer active, can you release its source code?

**Comment by MrSypz** [comment]
**I'm curious how you know this mod is no longer active!**  
I'm actually still adding more features, but I'm not going to release them soon due to many bugs and crashes. This includes a few features that I've backported, and I'm planning to make it compatible with *Penomior*.

I'd recommend using **TieredZ 1.20.1** instead, as it's far better than this mod. By the way, this mod is a copycat of TieredZ.

But if you want a 1.20.1 version, I have one from before Mojang changed everything, which caused my mod to break. I coded it for 1.19.4, and it broke with every version update as Mojang kept changing things.

![image](https://github.com/user-attachments/assets/2e3a5a66-2742-47ad-b1d6-93c6491c2f72)
![image](https://github.com/user-attachments/assets/41c97593-0058-4a69-8389-f0bba1c3341a)

**Comment by xllifi** [comment]
![Screenshot_2024-09-01-12-00-22-04_984e1414ae90666a90f12ff17ec14a7f.jpg](https://github.com/user-attachments/assets/923cc92b-cab9-46c1-bae2-f6eb4aad4f3f)

My friend needs this mod for critical chance and damage, not for it being TieredZ copycat

**Comment by MrSypz** [comment]
> ![Screenshot_2024-09-01-12-00-22-04_984e1414ae90666a90f12ff17ec14a7f.jpg](https://private-user-images.githubusercontent.com/70767436/363452481-923cc92b-cab9-46c1-bae2-f6eb4aad4f3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzI4MDQsIm5iZiI6MTcyNTE3MjUwNCwicGF0aCI6Ii83MDc2NzQzNi8zNjM0NTI0ODEtOTIzY2M5MmItY2FiOS00NmMxLWJhZTItZjZlYjRhYWQ0ZjNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA2MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZDY2N2M5YzUyMWZmMGU0YjNkYTdiYTA5ZmNlZmNhMzAyNTkyMmI3NDM4NDM1MzQzNDNmMjUzYzE0NjY1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bqD_me-_JLZd0TXHbB_8qTuGvpmiTclNsTL86CrE1uY)
> 
> My friend needs this mod for critical chance and damage, not for it being TieredZ copycat

thank you to remind me I didn't change that part yet
